version: '3.8'
services:
  wol:
    container_name: wol
    image: ghcr.io/emberlightvfx/docker-wol:latest
    restart: unless-stopped
    environment:
      - FLET_SERVER_PORT=8080
    network_mode: host
