version: '3.8'
services:
  webapp:
    ports:
      - '8080:8080'
    network_mode: host
    restart: always
    container_name: wol
    image: emberlight/wol:latest
    environment:
      - FLET_SERVER_PORT=8080
